//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.DemoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpData", Namespace="http://schemas.datacontract.org/2004/07/Demo")]
    [System.SerializableAttribute()]
    public partial class EmpData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpIdField, value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpName {
            get {
                return this.EmpNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpNameField, value) != true)) {
                    this.EmpNameField = value;
                    this.RaisePropertyChanged("EmpName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DemoServiceReference.IDemo")]
    public interface IDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemo/GetEmpData", ReplyAction="http://tempuri.org/IDemo/GetEmpDataResponse")]
        string GetEmpData(Client.DemoServiceReference.EmpData empData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemo/GetEmpData", ReplyAction="http://tempuri.org/IDemo/GetEmpDataResponse")]
        System.Threading.Tasks.Task<string> GetEmpDataAsync(Client.DemoServiceReference.EmpData empData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoChannel : Client.DemoServiceReference.IDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoClient : System.ServiceModel.ClientBase<Client.DemoServiceReference.IDemo>, Client.DemoServiceReference.IDemo {
        
        public DemoClient() {
        }
        
        public DemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmpData(Client.DemoServiceReference.EmpData empData) {
            return base.Channel.GetEmpData(empData);
        }
        
        public System.Threading.Tasks.Task<string> GetEmpDataAsync(Client.DemoServiceReference.EmpData empData) {
            return base.Channel.GetEmpDataAsync(empData);
        }
    }
}
