//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelModel", Namespace="http://schemas.datacontract.org/2004/07/Demo")]
    [System.SerializableAttribute()]
    public partial class HotelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ratingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHotelFunctions")]
    public interface IHotelFunctions {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelFunctions/GetAllhotels", ReplyAction="http://tempuri.org/IHotelFunctions/GetAllhotelsResponse")]
        Client.ServiceReference1.HotelModel[] GetAllhotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelFunctions/GetAllhotels", ReplyAction="http://tempuri.org/IHotelFunctions/GetAllhotelsResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.HotelModel[]> GetAllhotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelFunctions/GetHotelByID", ReplyAction="http://tempuri.org/IHotelFunctions/GetHotelByIDResponse")]
        Client.ServiceReference1.HotelModel[] GetHotelByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelFunctions/GetHotelByID", ReplyAction="http://tempuri.org/IHotelFunctions/GetHotelByIDResponse")]
        System.Threading.Tasks.Task<Client.ServiceReference1.HotelModel[]> GetHotelByIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelFunctionsChannel : Client.ServiceReference1.IHotelFunctions, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelFunctionsClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IHotelFunctions>, Client.ServiceReference1.IHotelFunctions {
        
        public HotelFunctionsClient() {
        }
        
        public HotelFunctionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelFunctionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelFunctionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelFunctionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference1.HotelModel[] GetAllhotels() {
            return base.Channel.GetAllhotels();
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.HotelModel[]> GetAllhotelsAsync() {
            return base.Channel.GetAllhotelsAsync();
        }
        
        public Client.ServiceReference1.HotelModel[] GetHotelByID(int id) {
            return base.Channel.GetHotelByID(id);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.HotelModel[]> GetHotelByIDAsync(int id) {
            return base.Channel.GetHotelByIDAsync(id);
        }
    }
}
